### ISSUE TITLE
Use PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [CarbonPackages/Carbon.Rollup#11]
### Plugins:
(if marked, they are ready for version 8)

- [ ] [postcss-import-alias] – [Issue](https://github.com/privatenumber/postcss-import-alias/issues/1)
- [ ] [postcss-easy-import] – [Issue](https://github.com/TrySound/postcss-easy-import/issues/40)
- [x] [Tailwind CSS] – [Issue](https://github.com/tailwindlabs/tailwindcss/issues/2396)
- [x] [postcss-nested]
- [x] [postcss-assets] – [Issue](https://github.com/borodean/postcss-assets/issues/86)
- [x] [postcss-url] – [Issue (postcss-import)](https://github.com/postcss/postcss-import/issues/427), [Issue](https://github.com/postcss/postcss-url/issues/147)
- [x] [postcss-normalize] – [Issue](https://github.com/csstools/postcss-normalize/issues/52)
- [ ] [postcss-preset-env] – [Issue](https://github.com/csstools/postcss-preset-env/issues/191)
- [ ] [postcss-easing-gradients] – [Issue](https://github.com/larsenwork/postcss-easing-gradients/issues/12)
- [ ] [postcss-for] – [Issue](https://github.com/antyakushev/postcss-for/issues/23)
- [x] [postcss-each] – [Issue](https://github.com/outpunk/postcss-each/issues/33)
- [ ] [postcss-hexrgba] – [Issue](https://github.com/seaneking/postcss-hexrgba/issues/31)
- [x] [postcss-clip-path-polyfill] – [Issue](https://github.com/komachi/postcss-clip-path-polyfill/issues/3)
- [ ] [postcss-responsive-type] – [Issue](https://github.com/seaneking/postcss-responsive-type/issues/39)
- [x] [postcss-easings]
- [ ] [pleeease-filters] – [Issue](https://github.com/iamvdo/pleeease-filters/issues/20)
- [ ] [postcss-quantity-queries] – [Issue](https://github.com/pascalduez/postcss-quantity-queries/issues/21)
- [x] [postcss-momentum-scrolling] – [Issue](https://github.com/yunusga/postcss-momentum-scrolling/issues/23)
- [x] [postcss-round-subpixels] – [Issue](https://github.com/himynameisdave/postcss-round-subpixels/issues/5)
- [x] [postcss-sort-media-queries] – [Issue](https://github.com/yunusga/postcss-sort-media-queries/issues/24)
- [x] [autoprefixer]
- [x] [cssnano] – [Issue](https://github.com/cssnano/cssnano/issues/952)
- [x] [postcss-banner] – [Issue](https://github.com/princed/postcss-banner/issues/106)
- [x] [postcss-reporter]

[postcss-import-alias]: https://www.npmjs.com/package/postcss-import-alias
[postcss-easy-import]: https://www.npmjs.com/package/postcss-easy-import
[postcss-nested]: https://www.npmjs.com/package/postcss-nested
[postcss-assets]: https://www.npmjs.com/package/postcss-assets
[postcss-url]: https://www.npmjs.com/package/postcss-url
[postcss-normalize]: https://www.npmjs.com/package/postcss-normalize
[postcss-preset-env]: https://preset-env.cssdb.org
[postcss-easing-gradients]: https://www.npmjs.com/package/postcss-easing-gradients
[easing-gradients]: https://larsenwork.com/easing-gradients
[postcss-for]: https://www.npmjs.com/package/postcss-for
[postcss-each]: https://www.npmjs.com/package/postcss-each
[postcss-hexrgba]: https://www.npmjs.com/package/postcss-hexrgba
[postcss-clip-path-polyfill]: https://www.npmjs.com/package/postcss-clip-path-polyfill
[postcss-responsive-type]: https://www.npmjs.com/package/postcss-responsive-type
[postcss-easings]: https://www.npmjs.com/package/postcss-easings
[pleeease-filters]: https://www.npmjs.com/package/pleeease-filters
[postcss-quantity-queries]: https://www.npmjs.com/package/postcss-quantity-queries
[postcss-momentum-scrolling]: https://www.npmjs.com/package/postcss-momentum-scrolling
[postcss-round-subpixels]: https://www.npmjs.com/package/postcss-round-subpixels
[postcss-sort-media-queries]: https://www.npmjs.com/package/postcss-sort-media-queries
[autoprefixer]: https://www.npmjs.com/package/autoprefixer
[cssnano]: https://cssnano.co
[postcss-banner]: https://www.npmjs.com/package/postcss-banner
[postcss-reporter]: https://www.npmjs.com/package/postcss-reporter
[tailwind css]: https://tailwindcss.com

**Comment by yunusga** [comment]
postcss-sort-media-queries [v2.0.3](https://github.com/yunusga/postcss-sort-media-queries/releases/tag/v2.0.3)

**Comment by jonnitto** [comment]
Carbon.Rollup now works with PostCSS 8. This ticket stays open till all packages are migrated.

**Comment by jonnitto** [comment]
New issue: https://github.com/CarbonPackages/Carbon.Pipeline/issues/4
